favicon: /favicon.ico

# Keywords of your site | 网站关键字
keywords: YP's Blog
# Head headline | 头部标题
header_title: YP's Blog
# Head description | 头部描述
header_description: 一个专注前端智能化开发的技术博客
# Link to your logo | logo地址
logo: images/logo.png
# Link to your banner_img | 首页banner图地址
banner_img: images/banner.jpg

menu:
  home:
    title: 主页
    url: /
    target: false
  archive:
    title: 全部
    url: /archives
    target: false
  AI:
    title: AI
    url: /categories/AI/
    target: false
  前端:
    title: 前端
    url: /categories/前端/
    target: false
  计算机:
    title: 计算机
    url: /categories/计算机/
    target: false
  语言:
    title: 语言
    url: /categories/语言/
    target: false
  专题:
    title: 专题
    url: /categories/专题/
    target: false

social:
  home:
    title: Blog
    url: https://iloveyou11.github.io/
    target: true
  github:
    title: Github
    url: https://github.com/iloveyou11
    target: true

# Content

# Excerpt length | 摘录长度
excerpt_length: 190
# Excerpt link | 摘录链接
excerpt_link: more>>
# New window open link | 新窗口打开文章
open_new_link: false
# Article default cover picture，size：350*150 | 文章默认封面图，尺寸：350*150
# cover_picture: images/banner.jpg
# Open background particles | 开启背景粒子
open_bg_particle: true
# Open animation in homepage and head | 开启主页及头部动画
open_animation: false

# Article

# Open toc | 是否开启toc
toc: true

# Open share | 是否开启分享
share: true

# Style customization | 样式定制
style:
  # Main color tone | 主色调
  main_color: "#4e72b8"

# Comments | 评论

# 畅言，输入appid和appkey
changyan_appid: false
changyan_appkey: false
# 友言，输入id
youyan_id: false
# disqus
disqus: false
# gitment  https://github.com/imsun/gitment
gitment:
  owner: false #你的 GitHub ID
  repo: "" #存储评论的 repo
  client_id: "" #client ID
  client_secret: "" #client secret
livere:
  on: true
  livere_uid: "MTAyMC81MDE5Mi8yNjY4Mg=="

# Analytics | 分析
# 站长分析，输入站点id
cnzz_analytics: false
# 百度分析，输入key值
baidu_analytics: false
# google analytics | google分析
google_analytics: false

# Footer

# Access statistics | “不蒜子”访问量统计
access_counter:
  on: true
  site_uv: 总访客数：
  site_pv: 总访问量：

# 添加字数统计
word_count: true
# 文章搜索
# local_search:
#   enable: true
#   # if auto, trigger search by changing input
#   # if manual, trigger search by pressing enter key or search button
#   trigger: auto
#   # show top n results per article, show all results by setting to -1
#   top_n_per_article: 1

# 增加网站分享功能
needmoreshare2:
  enable: true
  postbottom:
    enable: true #是否开启博客分享按钮
    options:
      iconStyle: box
      boxForm: horizontal
      position: bottomCenter
      networks: Weibo,Wechat,Douban,QQZone,Twitter,Facebook
  float:
    enable: true #网站分享按钮
    options:
      iconStyle: box
      boxForm: horizontal
      position: middleRight
      networks: Weibo,Wechat,Douban,QQZone,Twitter,Facebook

# 加速鼠标反应
fastclick: true
# 增加站内搜索
# local_search:
#   enable: true
